/*******************************************************************************
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      https://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

// Some portions generated by IBM Bob
/* 
    Adoptium machines have an ansible.log file which saves the SHA of the last
    executed infrastructure playbook. This class retrieves and displays the SHA
    if the log file is present
 */

package org.testKitGen;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;

public class AnsibleLogReader {
    
    private static final String UNIX_LOG_PATH = "/var/log/ansible.log";
    private static final String WINDOWS_LOG_PATH = "ansible.log";

    public static String getAnsibleLogPath() {
        String osName = System.getProperty("os.name").toLowerCase();
        
        if (osName.contains("win")) {
            // Windows: $HOME/ansible.log
            String homeDir = System.getProperty("user.home");
            return homeDir + File.separator + WINDOWS_LOG_PATH;
        } else {
            return UNIX_LOG_PATH;
        }
    }

    // Check if the ansible.log file exists
    public static boolean ansibleLogExists() {
        String logPath = getAnsibleLogPath();
        File logFile = new File(logPath);
        return logFile.exists() && logFile.isFile();
    }

    public static String readLastLine() {
        String logPath = getAnsibleLogPath();
        
        if (!ansibleLogExists()) {
            System.err.println("Ansible log file not found at: " + logPath);
            System.out.println("================================================");
            return null;
        }
        
        try (RandomAccessFile file = new RandomAccessFile(logPath, "r")) {
            long fileLength = file.length();
            if (fileLength == 0) {
                return null;
            }
            
            StringBuilder lastLine = new StringBuilder();
            long pointer = fileLength - 1;
            
            // Read backwards from end of file
            while (pointer >= 0) {
                file.seek(pointer);
                char c = (char) file.read();
                
                if (c == '\n' || c == '\r') {
                    if (lastLine.length() > 0) {
                        break;
                    }
                } else {
                    lastLine.insert(0, c);
                }
                pointer--;
            }
            
            return lastLine.toString();
        } catch (IOException e) {
            System.err.println("Error reading ansible log file: " + e.getMessage());
            System.out.println("================================================");
            e.printStackTrace();
            return null;
        }
    }

    public static String getDateTimeAndSHA() {
        String lastLine = readLastLine();
        
        if (lastLine == null || lastLine.trim().isEmpty()) {
            System.err.println("No last line found in ansible log.");
            System.out.println("================================================");
            return null;
        }
        
        // Split the line by whitespace
        String[] parts = lastLine.trim().split("\\s+");
        
        if (parts.length >= 4) {
            String date = parts[1];
            String time = parts[2];
            String sha = parts[3];
            return date + " " + time + " " + sha;
        } else {
            System.err.println("Unexpected format in last line: " + lastLine);
            System.out.println("================================================");
            return null;
        }
    }

    public static void outputDateTimeAndSHA() {
        String logPath = getAnsibleLogPath();
        System.out.println("================================================");
        System.out.println("Checking for ansible.log at: " + logPath);
        
        if (!ansibleLogExists()) {
            System.out.println("Ansible log file not found.");
            System.out.println("================================================");
            return;
        }
        
        System.out.println("Ansible log file found.");
        String dateTimeAndSHA = getDateTimeAndSHA();
        
        if (dateTimeAndSHA != null) {
            System.out.println("Last deployment: " + dateTimeAndSHA);
            System.out.println("================================================");
        }
    }
}
